name: he-quan-tri-csdl

services:
  mongodb:
    image: mongo:8.0.5
    container_name: he-quan-tri-csdl-mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-keyfile:/data/mongodb-keyfile
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/data/mongodb-keyfile"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_data: